package main

const (
	structFieldConstTmpl = `// Code generated by github.com/995933447/structfieldconstgen. DO NOT EDIT.
package {{.OutPkg}}

const ({{range $field:=.Fields}}
	{{$.ConstPrefix}}{{$field.Name}}{{$.ConstSuffix}} = "{{$field.ConstVal}}"{{end}}
)`
)
